import { Phone, Calendar, Home, Utensils, Wrench, FileText, Activity, FileEdit, Mail, MessageSquare, Users, Headphones, BarChart3, MessageCircle, Workflow, Mic, LucideIcon } from "lucide-react";

export interface Product {
  id: number;
  name: string;
  slug: string;
  type: "workflow" | "voice_agent";
  category: string;
  niche: string;
  price: number;
  thumbnail: string;
  rating: number;
  reviews: number;
  description: string;
  shortDescription: string;
  features: string[];
  apps: string[];
  includes: string[];
  pack?: string;
  icon: LucideIcon;
  color: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Plumber Voice Agent",
    slug: "plumber-voice-agent",
    type: "voice_agent",
    category: "Voice Agents",
    niche: "Plumbing",
    price: 29,
    thumbnail: "wf_diagram_01_plumber.png",
    rating: 5,
    reviews: 12,
    description: "A high-performance voice agent for plumbers. Handles appointment scheduling and emergency dispatch. It can classify calls as 'emergency' vs 'general inquiry' and route them accordingly.",
    shortDescription: "Voice-powered lead capture for plumbing businesses",
    features: ["Emergency call detection", "Lead scoring", "Slack alerts", "SMS follow-up"],
    apps: ["Retell AI", "Supabase", "Slack", "Twilio"],
    includes: ["Retell Agent JSON", "n8n Workflow JSON", "Prompt Template", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Phone,
    color: "bg-blue-50 text-blue-600"
  },
  {
    id: 2,
    name: "Dental Appointment Booking",
    slug: "dental-appointment-booking",
    type: "voice_agent",
    category: "Voice Agents",
    niche: "Dental",
    price: 29,
    thumbnail: "wf_diagram_02_dental.png",
    rating: 5,
    reviews: 8,
    description: "Automate dental bookings with a friendly AI voice. Synchronizes directly with patient management systems and handles insurance information capture.",
    shortDescription: "Automated dental appointment booking via voice and SMS",
    features: ["Smart scheduling", "SMS confirmations", "Insurance capture", "Calendar sync"],
    apps: ["Retell AI", "Cal.com", "Twilio", "Supabase"],
    includes: ["Retell Agent JSON", "n8n Workflow JSON", "Scheduling Logic", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Calendar,
    color: "bg-emerald-50 text-emerald-600"
  },
  {
    id: 3,
    name: "Real Estate Lead Qualification",
    slug: "real-estate-lead-qualification",
    type: "voice_agent",
    category: "Voice Agents",
    niche: "Real Estate",
    price: 29,
    thumbnail: "wf_diagram_03_realestate.png",
    rating: 4,
    reviews: 15,
    description: "Qualify real estate leads 24/7. Extracts budget, location preferences, and urgency. Syncs data directly to your CRM of choice.",
    shortDescription: "AI-powered lead scoring and CRM sync for real estate",
    features: ["Budget-based scoring", "Timeline assessment", "Pre-approval tracking", "CRM sync"],
    apps: ["Supabase", "Zapier", "HubSpot", "Retell AI"],
    includes: ["Retell Agent JSON", "CRM Sync Workflow", "Scoring Logic", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Home,
    color: "bg-indigo-50 text-indigo-600"
  },
  {
    id: 4,
    name: "Restaurant WhatsApp Order",
    slug: "restaurant-whatsapp-order",
    type: "voice_agent",
    category: "Voice Agents",
    niche: "Restaurant",
    price: 29,
    thumbnail: "wf_diagram_04_restaurant.png",
    rating: 5,
    reviews: 22,
    description: "Let customers order via WhatsApp. Seamlessly integrates with POS systems and handles order parsing, price calculation, and confirmations.",
    shortDescription: "WhatsApp order bot for restaurants",
    features: ["Order parsing", "Price calculation", "Confirmations", "Special instructions"],
    apps: ["WhatsApp Business API", "Supabase", "n8n", "Stripe"],
    includes: ["WhatsApp Bot Workflow", "Price Engine", "Stripe Integration", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Utensils,
    color: "bg-amber-50 text-amber-600"
  },
  {
    id: 5,
    name: "HVAC Emergency Dispatch",
    slug: "hvac-emergency-dispatch",
    type: "voice_agent",
    category: "Voice Agents",
    niche: "HVAC",
    price: 29,
    thumbnail: "wf_diagram_05_hvac.png",
    rating: 5,
    reviews: 7,
    description: "Urgent dispatch for HVAC professionals. Prioritizes emergency calls and routes to on-call technicians automatically based on location and availability.",
    shortDescription: "Emergency dispatch system for HVAC technicians",
    features: ["Temperature detection", "Auto-calling", "Alert routing", "Technician mobile alerts"],
    apps: ["Twilio", "Slack", "Supabase", "VAPI"],
    includes: ["VAPI Agent JSON", "Dispatch Workflow", "Slack Alerts", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Wrench,
    color: "bg-rose-50 text-rose-600"
  },
  {
    id: 6,
    name: "Cleaning Service Quote",
    slug: "cleaning-service-quote",
    type: "workflow",
    category: "Workflows",
    niche: "Cleaning",
    price: 29,
    thumbnail: "wf_diagram_06_cleaning.png",
    rating: 4,
    reviews: 19,
    description: "Automated quoting for cleaning services. Calculates price based on rooms, frequency, and extras. Delivers a professional PDF quote immediately.",
    shortDescription: "Automated quote calculator for cleaning services",
    features: ["Sqft-based pricing", "Multi-service support", "PDF quotes", "Email automation"],
    apps: ["Gemini", "Resend", "Supabase", "n8n"],
    includes: ["Price Calculator Workflow", "PDF Template", "Email Templates", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: FileText,
    color: "bg-cyan-50 text-cyan-600"
  },
  {
    id: 7,
    name: "Fitness Coach Follow-Up",
    slug: "fitness-coach-followup",
    type: "workflow",
    category: "Workflows",
    niche: "Fitness",
    price: 29,
    thumbnail: "wf_diagram_07_fitness.png",
    rating: 5,
    reviews: 11,
    description: "Boost retention with automated follow-ups. Sends personalized encouragement and check-ins based on workout gaps and membership status.",
    shortDescription: "Client follow-up automation for fitness coaches",
    features: ["Workout gap tracking", "Priority-based messaging", "Goal tracking", "Automated SMS"],
    apps: ["Twilio", "Resend", "Supabase", "n8n"],
    includes: ["Retention Workflow", "SMS Templates", "Goal Tracking Logic", "Setup Guide"],
    pack: "Niche Voice Agents Pack",
    icon: Activity,
    color: "bg-green-50 text-green-600"
  },
  {
    id: 8,
    name: "Content Repurposing",
    slug: "content-repurposing",
    type: "workflow",
    category: "Workflows",
    niche: "Marketing",
    price: 29,
    thumbnail: "wf_diagram_08_content.png",
    rating: 5,
    reviews: 34,
    description: "Turn one video or blog post into 10+ social formats. Uses AI to extract hooks, summaries, and key points for Twitter, LinkedIn, and more.",
    shortDescription: "Transform one content piece into multiple social formats",
    features: ["Twitter threads", "LinkedIn posts", "Instagram captions", "TikTok scripts"],
    apps: ["Gemini", "Supabase", "n8n", "YouTube API"],
    includes: ["Repurposing Workflow", "AI Prompt Library", "Social Templates", "Setup Guide"],
    pack: "AI Marketing Pack",
    icon: FileEdit,
    color: "bg-indigo-50 text-indigo-600"
  },
  {
    id: 9,
    name: "Lead Magnet Generator",
    slug: "lead-magnet-generator",
    type: "workflow",
    category: "Workflows",
    niche: "Marketing",
    price: 29,
    thumbnail: "wf_diagram_09_leadmagnet.png",
    rating: 4,
    reviews: 28,
    description: "Create high-converting lead magnets in minutes. Just provide a topic and get a structured, professional-looking PDF ready for your audience.",
    shortDescription: "AI-powered lead magnet content generator",
    features: ["Multi-format output", "Brand voice adaptation", "PDF-ready content", "Email delivery"],
    apps: ["Gemini", "Supabase", "n8n", "Google Docs"],
    includes: ["Generator Workflow", "PDF Generator", "Brand Voice Settings", "Setup Guide"],
    pack: "AI Marketing Pack",
    icon: Mail,
    color: "bg-rose-50 text-rose-600"
  },
  {
    id: 10,
    name: "Cold Email Personalizer",
    slug: "cold-email-personalizer",
    type: "workflow",
    category: "Workflows",
    niche: "Marketing",
    price: 29,
    thumbnail: "wf_diagram_11_coldemail.png",
    rating: 4,
    reviews: 16,
    description: "Hyper-personalized cold outreach at scale. Researches prospects on LinkedIn and writes unique openers that increase response rates.",
    shortDescription: "Hyper-personalized cold email generator from LinkedIn",
    features: ["LinkedIn analysis", "Personalization hooks", "Multi-variant output", "CRM integration"],
    apps: ["Gemini", "Hunter.io", "Resend", "n8n"],
    includes: ["Outreach Workflow", "Scraping Logic", "Prompt Library", "Setup Guide"],
    pack: "AI Marketing Pack",
    icon: MessageSquare,
    color: "bg-violet-50 text-violet-600"
  },
  {
    id: 11,
    name: "Meeting Summarizer",
    slug: "meeting-summarizer",
    type: "workflow",
    category: "Workflows",
    niche: "Business",
    price: 29,
    thumbnail: "wf_diagram_10_meeting.png",
    rating: 5,
    reviews: 45,
    description: "Automatic meeting notes and action items. Connects to Zoom or Google Meet recordings and syncs summaries to your team's workspace.",
    shortDescription: "Extract decisions and action items from meetings",
    features: ["AI summarization", "Action item extraction", "Team emails", "Sentiment analysis"],
    apps: ["Gemini", "Resend", "Supabase", "n8n"],
    includes: ["Summary Workflow", "Action Item Parser", "Email Templates", "Setup Guide"],
    pack: "Business Operations Pack",
    icon: Users,
    color: "bg-amber-50 text-amber-600"
  },
  {
    id: 12,
    name: "Support Ticket Router",
    slug: "support-ticket-router",
    type: "workflow",
    category: "Workflows",
    niche: "Support",
    price: 29,
    thumbnail: "wf_diagram_12_support.png",
    rating: 5,
    reviews: 21,
    description: "Smart routing for support tickets. Categorizes by sentiment, urgency, and subject matter automatically to reduce response time.",
    shortDescription: "AI-powered ticket classification and routing",
    features: ["Auto-classification", "Sentiment analysis", "Auto-resolve simple queries", "Priority routing"],
    apps: ["Gemini", "Slack", "Supabase", "Zendesk"],
    includes: ["Routing Workflow", "Sentiment Engine", "Slack Integration", "Setup Guide"],
    pack: "Business Operations Pack",
    icon: Headphones,
    color: "bg-teal-50 text-teal-600"
  },
  {
    id: 13,
    name: "Competitor Price Monitor",
    slug: "competitor-price-monitor",
    type: "workflow",
    category: "Workflows",
    niche: "Business",
    price: 29,
    thumbnail: "wf_diagram_13_price.png",
    rating: 4,
    reviews: 9,
    description: "Track competitor pricing in real-time. Sends alerts when prices change or when new trends emerge in your market niche.",
    shortDescription: "Competitor price monitoring with AI insights",
    features: ["6-hour intervals", "Trend analysis", "Slack alerts", "Historical tracking"],
    apps: ["ScraperAPI", "Gemini", "Slack", "n8n"],
    includes: ["Monitoring Workflow", "Price Scraper", "Alert Logic", "Setup Guide"],
    pack: "Business Operations Pack",
    icon: BarChart3,
    color: "bg-orange-50 text-orange-600"
  },
  {
    id: 14,
    name: "Resume Screening",
    slug: "resume-screening",
    type: "workflow",
    category: "Workflows",
    niche: "HR",
    price: 29,
    thumbnail: "wf_diagram_14_resume.png",
    rating: 5,
    reviews: 33,
    description: "Screen thousands of resumes in seconds. Matches skills and experience to job descriptions with high accuracy using advanced LLM reasoning.",
    shortDescription: "AI-powered candidate screening and ranking",
    features: ["Match scoring", "Skills analysis", "Interview questions generator", "Shortlist automation"],
    apps: ["Gemini", "Resend", "Supabase", "n8n"],
    includes: ["Screening Workflow", "Ranking Logic", "Interview Generator", "Setup Guide"],
    pack: "Business Operations Pack",
    icon: FileText,
    color: "bg-violet-50 text-violet-600"
  },
  {
    id: 15,
    name: "Social Comment Responder",
    slug: "social-comment-responder",
    type: "workflow",
    category: "Workflows",
    niche: "Marketing",
    price: 29,
    thumbnail: "wf_diagram_15_social.png",
    rating: 4,
    reviews: 27,
    description: "Engage with your audience automatically. Responds to social comments with brand-consistent AI that knows when to pivot to a sale.",
    shortDescription: "Auto-generate on-brand replies to social comments",
    features: ["Brand voice matching", "Sentiment detection", "CTA inclusion", "Auto-posting"],
    apps: ["Gemini", "Supabase", "n8n", "Instagram Graph API"],
    includes: ["Responder Workflow", "Sentiment Filter", "Brand Voice Profile", "Setup Guide"],
    pack: "Business Operations Pack",
    icon: MessageCircle,
    color: "bg-rose-50 text-rose-600"
  },
];

export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
